# Problem Statement
You have been given a cleaned-looking Food Delivery Orders dataset. Your task is to inspect the data in
Jupyter Notebook, perform a short EDA, identify the controlled data-quality issues, correct them using
Pandas, create one new analytical column, and answer the business questions given below.
At the end, for every business output, also write which Power BI visual you would use to present that
result on a dashboard.

## Part A - Quick EDA and Data Inspection

In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_excel('Food_Delivery_dataset.xlsx')
df.head()

,Order_ID,Customer_ID,Order_Date,City,Area,Food_Category,Restaurant_Type,Payment_Method,Order_Amount,Delivery_Minutes,Rating,Promo_Used
0,ORD00001,CUST0001,2026-05-03,Karachi,Gulshan-e-Iqbal,Chinese,Fast Food,Card,1420,55,3,No
1,ORD00002,CUST0002,2026-05-02,Karachi,Clifton,Chinese,Casual Dining,Card,1880,51,3,No
2,ORD00003,CUST0003,2026-05-08,Lahore,Wapda Town,Healthy,Casual Dining,Cash,1090,55,1,No
3,ORD00004,CUST0004,2026-05-26,Islamabad,Blue Area,Burgers,Cloud Kitchen,Card,1050,36,4,Yes
4,ORD00005,CUST0005,2026-05-14,Lahore,Johar Town,Desi,Casual Dining,Card,1180,20,5,No

In [3]:
df.shape

(1200, 12)

In [4]:
df.columns

Index(['Order_ID', 'Customer_ID', 'Order_Date', 'City', 'Area',
       'Food_Category', 'Restaurant_Type', 'Payment_Method', 'Order_Amount',
       'Delivery_Minutes', 'Rating', 'Promo_Used'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          1200 non-null   object
 1   Customer_ID       1200 non-null   object
 2   Order_Date        1200 non-null   datetime64[ns]
 3   City              1200 non-null   object
 4   Area              1200 non-null   object
 5   Food_Category     1200 non-null   object
 6   Restaurant_Type   1200 non-null   object
 7   Payment_Method    1200 non-null   object
 8   Order_Amount      1200 non-null   int64
 9   Delivery_Minutes  1200 non-null   int64
 10  Rating            1200 non-null   int64
 11  Promo_Used        1200 non-null   object
dtypes: datetime64[ns](1), int64(3), object(8)
memory usage: 112.6+ KB

In [6]:
df.isnull().sum()

Order_ID            0
Customer_ID         0
Order_Date          0
City                0
Area                0
Food_Category       0
Restaurant_Type     0
Payment_Method      0
Order_Amount        0
Delivery_Minutes    0
Rating              0
Promo_Used          0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.describe()

                Order_Date  Order_Amount  Delivery_Minutes       Rating
count                 1200   1200.000000       1200.000000  1200.000000
mean   2026-05-23 13:55:12   1144.216667         38.906667     3.846667
min    2026-05-01 00:00:00    300.000000         18.000000     1.000000
25%    2026-05-12 00:00:00    760.000000         29.000000     3.000000
50%    2026-05-23 12:00:00   1110.000000         37.000000     4.000000
75%    2026-06-04 06:00:00   1470.000000         45.000000     5.000000
max    2026-06-15 00:00:00   2490.000000         76.000000     5.000000
std                    NaN    484.731737         13.207763     0.943697

## Part B - Controlled Cleaning

In [9]:
df['Payment_Method'] = df['Payment_Method'].replace({
    'cash': 'Cash',
    'CARD': 'Card',
    'E-Wallet':'Wallet'
})

In [10]:
df['Payment_Method'].head(20)

0       Card
1       Card
2       Cash
3       Card
4       Card
5     Wallet
6       Cash
7       Card
8     Wallet
9       Cash
10      Card
11      Card
12      Card
13      Cash
14    Wallet
15      Cash
16      Cash
17      Cash
18      Cash
19    Wallet
Name: Payment_Method, dtype: object

In [11]:
conditions = [
    df['Delivery_Minutes'] > 45,
    (df['Delivery_Minutes'] > 30) & (df['Delivery_Minutes'] <= 45),
    df['Delivery_Minutes'] <= 30
]

choices = ['Delayed', 'Normal', 'Fast']

df['Delivery_Speed'] = np.select(
    conditions,
    choices,
    default='Unknown'
)

In [12]:
df.head(20)

,Order_ID,Customer_ID,Order_Date,City,Area,Food_Category,Restaurant_Type,Payment_Method,Order_Amount,Delivery_Minutes,Rating,Promo_Used,Delivery_Speed
0,ORD00001,CUST0001,2026-05-03,Karachi,Gulshan-e-Iqbal,Chinese,Fast Food,Card,1420,55,3,No,Delayed
1,ORD00002,CUST0002,2026-05-02,Karachi,Clifton,Chinese,Casual Dining,Card,1880,51,3,No,Delayed
2,ORD00003,CUST0003,2026-05-08,Lahore,Wapda Town,Healthy,Casual Dining,Cash,1090,55,1,No,Delayed
3,ORD00004,CUST0004,2026-05-26,Islamabad,Blue Area,Burgers,Cloud Kitchen,Card,1050,36,4,Yes,Normal
4,ORD00005,CUST0005,2026-05-14,Lahore,Johar Town,Desi,Casual Dining,Card,1180,20,5,No,Fast
5,ORD00006,CUST0006,2026-05-10,Rawalpindi,Saddar,Desi,Fast Food,Wallet,1710,59,4,No,Delayed
6,ORD00007,CUST0007,2026-05-02,Lahore,DHA Lahore,Bakery,Bakery,Cash,500,48,3,No,Delayed
7,ORD00008,CUST0008,2026-05-29,Islamabad,F-10,Pizza,Casual Dining,Card,1050,20,5,No,Fast
8,ORD00009,CUST0009,2026-06-13,Karachi,Gulshan-e-Iqbal,Desi,Cloud Kitchen,Wallet,1550,18,3,Yes,Fast
9,ORD00010,CUST0010,2026-06-03,Karachi,DHA,Desi,Fast Food,Cash,1090,38,4,No,Normal
10,ORD00011,CUST0011,2026-05-15,Karachi,PECHS,Beverages,Cafe,Card,310,39,5,No,Normal
11,ORD00012,CUST0012,2026-05-02,Lahore,Johar Town,Beverages,Cafe,Card,500,23,3,Yes,Fast
12,ORD00013,CUST0013,2026-05-13,Karachi,Gulshan-e-Iqbal,Desi,Casual Dining,Card,1610,31,4,No,Normal
13,ORD00014,CUST0014,2026-06-07,Lahore,Johar Town,Pizza,Fast Food,Cash,1050,33,3,Yes,Normal
14,ORD00015,CUST0015,2026-05-08,Karachi,DHA,Burgers,Fast Food,Wallet,1130,52,3,No,Delayed
15,ORD00016,CUST0016,2026-05-16,Lahore,Gulberg,Healthy,Cafe,Cash,940,29,5,No,Fast
16,ORD00017,CUST0017,2026-05-25,Lahore,Gulberg,Beverages,Cloud Kitchen,Cash,470,27,5,No,Fast
17,ORD00018,CUST0018,2026-05-22,Karachi,Gulshan-e-Iqbal,Bakery,Cafe,Cash,870,46,3,No,Delayed
18,ORD00019,CUST0019,2026-06-05,Islamabad,I-8,Pizza,Fast Food,Cash,1940,52,3,Yes,Delayed
19,ORD00020,CUST0020,2026-05-24,Karachi,North Nazimabad,Pizza,Fast Food,Wallet,880,67,3,No,Delayed

## Part C - Business Questions

1. How many Total Orders are in the dataset?

In [13]:
print('Total Orders:',df['Order_ID'].size)

Total Orders: 1200

### Power BI Visual - Card

2. How many Unique Customers are there?

In [14]:
df['Customer_ID'].value_counts()

Customer_ID
CUST0201    8
CUST0163    8
CUST0098    8
CUST0166    8
CUST0050    7
           ..
CUST0192    1
CUST0195    1
CUST0198    1
CUST0323    1
CUST0420    1
Name: count, Length: 420, dtype: int64

In [15]:
print('Unique Customers:',df['Customer_ID'].nunique())

Unique Customers: 420

### Power BI Visual - Card

3. What is the Average Delivery Time?

In [16]:
print('Average Delivery Time:',df['Delivery_Minutes'].mean().round(),'minutes')

Average Delivery Time: 39.0 minutes

### Power BI Visual - Card

4. Which are the Top 5 Areas by number of Orders?

In [17]:
top_5_areas = (
    df.groupby('Area')['Order_ID']
      .nunique()
      .sort_values(ascending=False)
      .head(5)
)

print(top_5_areas)

Area
Gulshan-e-Iqbal    140
DHA                104
North Nazimabad     98
Clifton             91
PECHS               87
Name: Order_ID, dtype: int64

In [18]:
df['Area'].value_counts().head(5)

Area
Gulshan-e-Iqbal    140
DHA                104
North Nazimabad     98
Clifton             91
PECHS               87
Name: count, dtype: int64

### Power BI Visual - Bar Chart

5. Compare Orders by Food Category.

In [19]:
df['Food_Category'].value_counts()

Food_Category
Desi         250
Burgers      210
Pizza        209
Chinese      175
Beverages    145
Bakery       116
Healthy       95
Name: count, dtype: int64

### Power BI Visual - Clustered Bar Chart

6. Show the Order Status distribution.

In [20]:
df['Payment_Method'].value_counts()

Payment_Method
Cash      534
Card      397
Wallet    269
Name: count, dtype: int64

### Power BI Visual - Donut Chart

8. Compare the Delivery_Speed categories (Fast, Normal, Delayed).

In [21]:
df['Delivery_Speed'].value_counts()

Delivery_Speed
Normal     554
Fast       355
Delayed    291
Name: count, dtype: int64

### Power BI Visual - Pie Chart

In [22]:


df.to_excel("Food_Delivery_dasboard_dataset.xlsx", index=False)

AttributeError: 'DataFrame' object has no attribute 'to_xlsx'